api/urls.py
from django.urls import include, path

from api.views import QwikJson, VenueMarksJson

urlpatterns = [
    path("", QwikJson.as_view(), name='default_json'),
    path("venue_marks/", VenueMarksJson.as_view(), name='venue_marks_json'),
]

appeal/urls.py
from django.urls import include, path

from appeal.views import AcceptView, BidView, AppealsView, KeenView, BidView, RivalView
from qwikgame.views import ServiceWorkerView

urlpatterns = [
    path("", AppealsView.as_view(), name='appeal'),
    path("<int:appeal>/", BidView.as_view(), name='bid'),
    path("<int:appeal>/<rival>/", RivalView.as_view()),
    path("<int:appeal>/<rival>/<path:ignore>", RivalView.as_view()),
    path("keen/", KeenView.as_view(), name='keen'),
    path("keen/<str:game>/", KeenView.as_view(), name='keen'),
    path("accept/<int:appeal>/", AcceptView.as_view(), name='accept'),
    path("accept/<int:appeal>/<rival>/", RivalView.as_view()),
    path('sw.js', ServiceWorkerView.as_view(), name='sw'),
]

player/urls.py
from django.urls import include, path

from player.views import AppealsView, FilterView, FriendView, FriendAddView, FriendsView, InvitationView, RivalView, FiltersView
from qwikgame.views import ServiceWorkerView

urlpatterns = [
    path("", AppealsView.as_view()),
    path("filter/", FilterView.as_view(), name='filter'),
    path("filters/", FiltersView.as_view(), name='filters'),
    path("friend/", FriendsView.as_view(), name='friend'),
    path("friend/add/", FriendView.as_view(), name='friend_add'),
    path("friend/<int:friend>/", FriendView.as_view(), name='friend'),
    path("rival/", RivalView.as_view(), name='rival'),
    path('sw.js', ServiceWorkerView.as_view(), name='sw'),
]

qwikgame/urls.py
from django.contrib import admin, auth
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView

from qwikgame.views import LicenseView, OfflineView, PrivacyView, QwikView, ServiceWorkerView, TermsView, WelcomeView

urlpatterns = [
    path('', WelcomeView.as_view(), name='welcome'),
    path("about/license/", LicenseView.as_view(), name='license'),
    path("about/privacy/", PrivacyView.as_view(), name='privacy'),
    path("about/terms/", TermsView.as_view(), name='terms'),
    path('account/', include("person.urls")),
    path('admin/', admin.site.urls),
    path('appeal/', include('appeal.urls')),
    path('api/', include('api.urls')),
    path('authenticate/', include('authenticate.urls')),
    path('game/', include('game.urls')),
    path("feedback/", include("feedback.urls")),
    path('offline.html', OfflineView.as_view(), name='offline'),
    path('player/', include('player.urls')),
    path('venue/', include('venue.urls')),
    path('webpush/', include('webpush.urls')),
    path('webpush/icon/', RedirectView.as_view(url='/static/img/qwik-icon.svg')),
    # The service worker cannot be in /static because its scope will be limited to /static.
    path('sw.js', ServiceWorkerView.as_view(), name='sw'),
]

game/models.py
import datetime, logging
from django.db import models
from django.utils.translation import gettext_lazy as _
from qwikgame.constants import DELAY_MATCH_PERISH_CHAT, DELAY_REVIEW_PERISH, SYSTEM_HASH, SYSTEM_NAME
from qwikgame.log import Entry

logger = logging.getLogger(__file__)


class Game(models.Model):
    code = models.CharField(max_length=3, primary_key=True)
    icon = models.CharField(max_length=48)
    name = models.CharField(max_length=32)

    @classmethod
    def choices(klass):
        try:
            return [(game.code, game.name) for game in klass.objects.order_by('name')]
        except:
            return []

    @classmethod
    def icons(klass):
        try:
            return {game.code: game.icon for game in klass.objects.all()}
        except:
            return {}

    def __str__(self):
        return self.name


class Match(models.Model):

    STATUS = {
        'A': 'active',
        'C': 'complete',
        'D': 'disabled',
        'X': 'cancelled',
    }

    date = models.DateTimeField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    log = models.JSONField(default=list)
    meta = models.JSONField(default=dict)
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    competitors = models.ManyToManyField("player.Player")
    venue = models.ForeignKey('venue.Venue', on_delete=models.CASCADE)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def __str__(self):
        names = [player.qwikname for player in self.competitors.all()]
        return f'{self.game} {names} {self.datetime_str} {self.venue}'

    @classmethod
    def from_bid(cls, bid):
        appeal = bid.appeal
        match = cls(
            date = bid.datetime,
            game = bid.appeal.game,
            log = bid.appeal.log.copy(),
            venue = bid.appeal.venue,
        )
        match.save()
        # important to add bid.appeal.player first to ensure lowest pk
        match.competitors.add(bid.appeal.player)
        match.competitors.add(bid.rival)
        match.save()
        return match

    def alert(self, type, instigator, text=''):
        context = {
            'date': self.date.strftime("%Y-%m-%d %A"),
            'game': self.game,
            'match': self,
            'text': text,
            'time': self.date.strftime("%Hh"),
            'venue': self.venue,
        }
        from player.models import Player
        recipients = list(self.competitors.all())
        recipients.remove(instigator)
        for recipient in recipients:
            rival = Player.objects.filter(pk=recipient.pk).first()
            if rival:
                context['name'] = rival.name_rival(instigator)
                rival.alert(
                    type=type,
                    expires=self.date + datetime.timedelta(days=1),
                    context=context,
                    url = f'/game/match/{self.pk}/',
                )

    def announce(self, instigator):
        logger.info(f'Announcing Match: {self}')
        self.alert('p', instigator)
        self.status = 'A'
        self.meta['seen'] = [instigator.pk]
        self.log_event('scheduled', instigator)
        self.log_event('book_prompt')

    def cancel(self, instigator):
        logger.info(f'Cancelling Match: {self}')
        self.alert('q', instigator)
        self.status = 'X'
        self.meta['seen'] = [instigator.pk]
        self.log_event('cancelled', instigator)

    def chat(self, instigator, text):
        self.alert('r', instigator, text)
        self.meta['seen'] = [instigator.pk]
        self.log_event('chat', instigator, text)

    def clear_conflicts(self, scheduled_appeal):
        from appeal.models import Bid, Appeal
        for bid in Bid.objects.filter(
                appeal__date=self.date,
                rival__in=self.competitors.all(),
            ).exclude(appeal=scheduled_appeal):
            bid.withdraw()
        for appeal in Appeal.objects.filter(
                player__in=self.competitors.all(),
                date=self.date.date()
            ).exclude(pk=scheduled_appeal.pk):
            appeal.hour_withdraw(self.date.hour)

    def competitor_names(self):
        return [player.qwikname for player in self.competitors.all()]

    @property
    def date_str(self):
        return self.datetime_aware.strftime('%d %b %Y')

    @property
    def datetime_aware(self):
        return self.date.astimezone(self.venue.tzinfo)
    
    @property
    def datetime_str(self):
        return self.datetime_aware.strftime('%d %b %Y, %Hh')

    def disable(self, dry_run=False):
        now = self.venue.now()
        if now > (self.date + DELAY_MATCH_CHAT):
            dry = 'dry_run' if dry_run else ''
            if not dry_run:
                self.status = 'D'
                self.log_event('disabled')
                self.save()
            logger.debug(f'match disabled {dry}: {self}')
            return 'chat'
        return 'noop'

    @property
    def hour_str(self):
        return self.datetime_aware.strftime('%Hh')

    def icons(self):
        from player.models import Player
        pks = list(self.competitors.values_list('pk', flat=True))
        players = Player.objects.filter(pk__in=pks)
        return {p.pk:p.icon for p in players}

    def init_player(self):
        # return the competitor with the first pk
        return self.competitors.order_by('pk').first()

    def log_clear(self):
        self.log = []
        self.save()

    def log_entry(self, entry):
        self.log.append(entry)
        self.save()

    def log_event(self, template, instigator=None, text=''):
        user = instigator.user if instigator else None
        person = user.person if user else None
        player = user.player if user else None
        entry = Entry(
            hash = user.hash if user else SYSTEM_HASH,
            id = player.pk if player else '',
            klass = template,
            name = person.qwikname if person else SYSTEM_NAME,
            text = text,
        )
        match template:
            case 'book_prompt':
                # link = f"<a href='{self.venue.url}' target='_blank'>{self.venue.url}</a>"
                entry['text'] = _(
                        "%(name)s, please contact venue to ensure availability on %(date)s : %(phone)s : %(url)s"
                    ) % {
                        'name': self.init_player().qwikname,
                        'date': self.datetime_str,
                        'phone': self.venue.phone,
                        'url': self.venue.url,
                    }
            case 'cancelled':
                entry['text'] = _('match cancelled')
            case 'chat':
                entry['text'] = text
            case 'disabled':
                entry['text'] = _('match chat disabled')
            case 'scheduled':
                entry['text'] = _('match scheduled')
            case 'perished':
                entry['text'] = _('match chat perished')
            case _:
                logger.warn(f'unknown template: {template}')
        self.log_entry(entry)

    def perish(self, dry_run=False):
        now = self.venue.now()
        if now > (self.date + DELAY_MATCH_PERISH_CHAT):
            dry = 'dry_run' if dry_run else ''
            if not dry_run:
                self.log_clear()
                self.log_event('perished')
                self.save()
            logger.debug(f'match perished {dry}: {self}')
            return 'chat'
        return 'noop'

    def mark_seen(self, player_pks=[]):
        seen = set(self.meta.get('seen', []))
        seen.update(player_pks)
        self.meta['seen'] = list(seen)
        return self

    def rivals(self, player):
        competitors = list(self.competitors.values_list('pk', flat=True))
        competitors.remove(player.pk)
        return competitors

    # format venue_time on server, rather than in template (user timezone)
    def venue_date_str(self):
        return self._venue_time().strftime("%d %b %Y")

    # format venue_time on server, rather than in template (user timezone)
    def venue_hour_str(self):
        return self._venue_time().strftime("%H")

    def _venue_time(self):
        return self.date.astimezone(self.venue.tzinfo)


class Review(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    meta = models.JSONField(default=dict)
    player = models.ForeignKey("player.Player", on_delete=models.CASCADE, related_name='reviewer')
    rival = models.ForeignKey("player.Player", on_delete=models.CASCADE, related_name='reviewee')

    def __str__(self):
        return f"{self.player}: {self.rival} {self.match}"

    def log_event(self, template):
        match template:
            case 'review':
                player = self.player
                user = player.user
                person = user.person
                entry = Entry(
                    hash = user.hash,
                    id = self.player.pk,
                    klass= 'reviewed',
                    name = person.qwikname,
                    text = f'reviewed the Match'
                )
            case _:
                logger.warn(f'unknown template: {template}')
        self.match.log_entry(entry)

    def mark_seen(self, player_pks=[]):
        seen = set(self.meta.get('seen', []))
        seen.update(player_pks)
        self.meta['seen'] = list(seen)
        return self

    def perish(self, dry_run=False):
        action = 'noop'
        now = self.match.venue.now()
        if now > self.match.date + DELAY_REVIEW_PERISH:
            if not dry_run:
                self.delete()
            action = 'expired'
        return action

player/templates/player/account_player.html
{% extends "person/account.html" %}

{% block player_public %}
                    <h2>
                        YOUR QWIKGAME REPUTATION
                        <div class="button info sml" data-visible="false">
                            <i class="fa-solid fa-info fa-1x"></i>
                            <div class="info_text hidden">Based on feedback given by your rivals</div>
                        </div>
                    </h2>
                    <div class="plank">
                        {% for _ in '12345'|make_list %} 
                        <div class="icon color">
                            {% if forloop.counter <= reputation %}
                            <i class="fa-solid fa-star fa-2x"></i>
                            {% else %}
                            <i class="fa-regular fa-star fa-2x"></i>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <h2>ABOUT</h2>

                    <div class="tab_area post">
                        <div class="tabs">
                            {% for preci in precis %}
                            <div class="button tab thin {% if forloop.first %} active {% endif %}" data-tab_id="{{ preci.game }}">
                                {{ preci.game }}
                            </div>
                            {% endfor %}
                        </div>
                        {% for preci in precis %}
                        <div id="{{ preci.game }}" class="tab_content {% if not forloop.first %} hidden {% endif %}">
                          <textarea id="" name="{{ preci.game }}" rows="4" cols="50">{{ preci.text }}</textarea>
                        </div>
                        {% endfor %}
                        <div class="button cta push_down wide schedule_save">
                            <p>SAVE</p>
                        </div>
                    </div>
{% endblock %}


{% block player_private %}
                    <h2>LIST OF BLOCKED PLAYERS</h2>
                    <div id="block_list" class="drop_down">
                        <div class="button drop" data-down="false">
                            <div>Blocked Players</div>
                            <div class="fat">v</div>
                        </div>
                        <div class="down hidden">
                            {% for block in blocked %}
                            <label class="option closable" for="{{ block }}">{{ block.name }} ({{ block.facet }})
                                <div class="button link push_right closer">unblock</div>
                            </label>
                            {% endfor %}
                        </div>
                    </div>
                    <fieldset id="block_add" class="hidden">
                        <input type="text" name="block" list="blocked" placeholder="Type email address"/>
                        <div class="rival-skill-learn grid_3_col">
                            <div class="button link show_block_list">Cancel</div>
                            <div class="button link">Learn more</div>
                            <div class="button ctb wide thin">Block</div>
                        </div>
                    </fieldset>
{% endblock %}

player/templates/player/account_public_snippet.html
<!-- qwikgame/player/templates/player/account_public_snippet.html -->
{% load i18n %}
    <div class="label">
        <label for="id_icon">
            {% translate "YOUR QWIKGAME REPUTATION" %}
        </label>
        <div class="btn secondary tiny round push_right info" data-visible="false">
            <i class="fa-solid fa-info fa-1x" aria-hidden="true"></i>
            <div class="info_text hidden">
                {% translate "Based on feedback given by your rivals." %}
            </div>
        </div>
    </div>
    <div class="plank">
{% include 'player/conduct_stars_snippet.html' %}
    </div>
    {{ player_form }}

player/templates/player/appeals.html
<!-- qwikgame/player/templates/player/appeals.html -->
{% extends "content.html" %}


{% block title %}Feed{% endblock %}


{% block cta_mobile %}
{% if small_screen %}
    <a class="btn special1 mobile" href="{% url 'keen' %}">
    <i class="fa-solid fa-paper-plane fa-3x"></i>
    </a>
{% endif %}
{% endblock %}


{% block cta_desktop %}
{% if big_screen %}
    <a class="btn special1" href="{% url 'keen' %}">
        <i class="fa-solid fa-paper-plane fa-xl"></i>
        <p>Invite</p>
    </a>
{% endif %}
{% endblock %}


{% block list %}
        <div id="alert_list_start" class="alert"></div>
        <div class="list_head">
            <div id="alert_list_head" class="alert"></div>
            <h1>Feed ({{ appeals_length }})</h1>
            <a class="btn secondary" href="{% url 'filters' %}">
                <i class="fa-solid fa-filter fa-1x"></i>
                Filter
            </a>
        </div>
        <div id="alert_list_group1" class="alert"></div>
        <h2 class="show_group">
            Participating
            <span>▲</span>
        </h2>
        <div class="post group">
{% for app in prospects %}
{% if app.player == player %}
            <a class="btn secondary item {{ app.seen }}" href="{% url 'accept' app.pk %}">
{% else %}
            <a class="btn secondary item {{ app.seen }}" href="{% url 'bid' app.pk %}">
{% endif %}
{% if app.pk == appeal.pk %}
                <input type="checkbox" name="selected" checked='checked' hidden>
{% endif %}
                <div class='lines'>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid {{ app.game.icon }} fa-1x"></i>
                        </span>
                        {{ app.game }}
                    </p>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid fa-calendar fa-1x"></i>
                        </span>
                        {{ app.date }}, {{ app.hours24 }}
                    </p>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid fa-location-dot fa-1x"></i>
                        </span>
                        {{ app.venue.place_str }}
                    </p>
                </div>
                <div class="badges">                        
                    <time datetime="{{ app.created_str }}" ></time>
                </div>
            </a>
{% empty %}
            <p>No accepted invitations!</p>
{% endfor %}
        </div>
        <div id="alert_list_group2" class="alert"></div>
        <h2 class="show_group">
            All
            <span>▲</span>
{% if filtered %}
            <a class="push_right" href="{% url 'filters' %}">filtered</a>
{% endif %}
        </h2>
        <div class="post group">
{% for app in appeals %}
            <a class="btn secondary item {{ app.seen }}" href="{% url 'bid' app.pk %}">
{% if app.pk == appeal.pk %}
                <input type="checkbox" name="selected" checked='checked' hidden>
{% endif %}
                <div class='lines'>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid {{ app.game.icon }} fa-1x"></i>
                        </span>
                        {{ app.game }}
                    </p>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid fa-calendar fa-1x"></i>
                        </span>
                        {{ app.date }}, {{ app.hours24 }}
                    </p>
                    <p class="line">
                        <span class="icon">
                            <i class="fa-solid fa-location-dot fa-1x"></i>
                        </span>
                        {{ app.venue.place_str }}
                    </p>
                </div>
                <div class="badges">                        
                    <time datetime="{{ app.created_str }}" ></time>
                </div>
            </a>
{% endfor %}
        </div>
        <div id="alert_list_end" class="alert"></div>
{% endblock %}


{% block detail %}
{% if big_screen %}
    <div id="detail" class="detail">
        <div id="alert_detail_start" class="alert"></div>
        <div class="pillar push_down">
            <div class="push_down">
                Open an Invitation<br>or send a new one!
            </div>
            <a class="btn special1 push_down" href="{% url 'keen' %}">
                <i class="fa-solid fa-paper-plane fa-xl"></i>
                Invite
            </a>
        </div>
        <div id="alert_detail_end" class="alert"></div>
    </div>
{% endif %}
{% endblock detail %}

player/templates/player/bid.html
<!-- qwikgame/player/templates/player/bid.html -->
{% extends "player/appeals.html" %}


{% block title %}Bid{% endblock %}

    
{% block list_bar %}
{% if big_screen %}
    {{ block.super }}
{% endif %}
{% endblock %}


{% block detail %}
    <div id="detail" class="detail">
        <div id="alert_detail_start" class="alert"></div>
        <div class="detail_head">
            <div id="alert_detail_head" class="alert"></div>
            <div class="icon">
                <i class="fa-solid fa-inbox fa-xl"></i>
            </div>
            <div class='head'>
                <p class="line">
                    <span class="icon">
                        <i class="fa-solid {{ appeal.game.icon }} fa-1x"></i>
                    </span>
                    {{ appeal.game }}
                </p>
                <p class="line">
                    <span class="icon">
                        <i class="fa-solid fa-calendar fa-1x"></i>
                    </span>
                    {{ appeal.date }}, {{ appeal.hours24 }}
                </p>
                <p class="line">
                    <span class="icon">
                        <i class="fa-solid fa-location-dot fa-1x"></i>
                    </span>
                    {{ appeal.venue.place_str }}
                </p>
            </div>
            <div class="drop_down icon head_more">
                <div class="btn drop" data-down="false">
                    <i class="fa-solid fa-ellipsis-vertical fa-2x"></i>
                </div>
                <div class="down hidden"></div>
            </div>
            <a class="btn special2 head_back" href="/player/appeal/{{ prev }}/">
                <i class="fa-solid fa-chevron-left fa-2x"></i>
            </a>
            <a class="btn special2 head_fwd" href="/player/appeal/{{ next }}/">
                <i class="fa-solid fa-chevron-right fa-2x"></i>
            </a>
        </div>
{% include 'player/rival_header_snippet.html' %}
        <div class="post">
            <div id="alert_detail_banner" class="alert"></div>
{% for entry in appeal.log %}
    {% if entry.id == player_id %}
            <div class="log_entry align_end {{ entry.klass }}">
    {% else %}
            <div class="log_entry align_start {{ entry.klass }}">
    {% endif %}
                <div class="btn special2">
                    <i class="fa-solid {{ entry.icon }} fa-2x"></i>
                </div>
                <div class="chat_bubble">
                    <span class="name">{{ entry.name }}</span>
                    <time datetime="{{ entry.created }}"></time>
                    <span class="text">{{ entry.text }}</span>
                </div>
    {% if bid %}
        {% if entry.pk == bid.pk %}
                <div class="drop_down icon head_more">
                    <div class="btn drop" data-down="false">
                        <i class="fa-solid fa-ellipsis-vertical fa-2x"></i>
                    </div>
                    <div class="down hidden">
                        <form id="form" action="{% url 'bid' appeal.pk %}" method="post">
            {% csrf_token %}
                            <label class="btn tertiary">
                                <input hidden form="form" name="CANCEL" type="submit" value='{{ bid.pk }}' onclick="return confirm('Cancel this Bid?')">
                                cancel
                            </label>
                        </form>
                    </div>
                </div>
        {% endif %}
    {% endif %}
            </div>
{% endfor %}
        </div>
        <div class="post todo">
            <div class="chat_item align_start">
                <div class="btn special2">
                    <i class="fa-brands fa-redhat fa-2x"></i>
                </div>
                <div class="chat_bubble">
                    <p class="bold">Venue Manager</p>
                    <p>Removed 15h from available hours</p>
                </div>
            </div>
            <div class="detail_chat_post"></div>
        </div>
{% if appeal.status == 'A' %}
    {% if bid %}
        <div class="pillar">
            <div class="nextup">
                <p>Awaiting Confirmation</p>
            </div>
        </div>
    {% else %}
        <div class="post form">
            <div id="alert_form_start" class="alert"></div>
            <form id='form' action="{% url 'bid' appeal.pk %}" method="post">
    {% csrf_token %}
    {{ bid_form }}
            <div class="paver">
                <div id="alert_form_submit" class="alert"></div>
                <label class="btn primary push_down">
                    <input hidden form="form" type="submit" name='accept'>
                    Accept
                </label>
            </div>
            </form>
            <div id="alert_form_end" class="alert"></div>
        </div>
    {% endif %}
{% elif appeal.status == 'C' %}
        <div class="pillar">
            <div class="nextup">
                <p>This Invitation has been cancelled</p>
            </div>
        </div>
{% elif appeal.status == 'D' %}
        <div class="pillar">
            <div class="nextup">
                <p>A Match has been confirmed for this Invitation</p>
            </div>
        </div>
{% elif appeal.status == 'X' %}
        <div class="pillar">
            <div class="nextup">
                <p>This Invitation has expired</p>
            </div>
        </div>
{% endif %}
        <div id="alert_detail_end" class="alert"></div>
    </div>
{% endblock %}

player/templates/player/friend_add.html
<!-- qwikgame/player/templates/player/friends.html -->
{% extends "player/friends.html" %}
{% load i18n %}


{% block title %}
    {% translate "Friends" %}
{% endblock %}

    
{% block list_bar %}
{% if big_screen %}
    {{ block.super }}
{% endif %}
{% endblock %}


{% block detail %}
    <div id="detail" class="detail">
        <div class="detail_head">
            <div class="icon selected">
                <i class="fa-solid fa-user-group fa-2x"></i>
            </div>
            <h2>{% translate "Add Friend" %}</h2>
        </div>
        <div class="post available_edit {{ hide_edit }}">
            <div class="post form">
                <form action="{% url 'friend_add' %}" method="post">
{% csrf_token %}
{{ form }}
                    <div class="pillar">
                        <label class="btn primary push_down">
                            <input hidden type="submit" name="ADD">
                            {% translate "Add" %}
                        </label>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

player/templates/player/private.html
<!-- qwikgame/player/templates/player/private.html -->
{% extends "person/private.html" %}


{% block player_private %}
                    <h2>LIST OF BLOCKED PLAYERS</h2>
                    <div id="block_list" class="drop_down">
                        <div class="button drop" data-down="false">
                            <div>Blocked Players</div>
                            <div class="fat">v</div>
                        </div>
                        <div class="down hidden">
                            {% for block in blocked %}
                            <label class="option closable" for="{{ block }}">{{ block.name }} ({{ block.facet }})
                                <div class="button link push_right closer">unblock</div>
                            </label>
                            {% endfor %}
                        </div>
                    </div>
                    <fieldset id="block_add" class="hidden">
                        <input type="text" name="block" list="blocked" placeholder="Type email address"/>
                        <div class="rival-skill-learn grid_3_col">
                            <div class="button link show_block_list">Cancel</div>
                            <div class="button link">Learn more</div>
                            <div class="button ctb wide thin">Block</div>
                        </div>
                    </fieldset>
{% endblock %}

player/templates/player/public.html
<!-- qwikgame/player/templates/player/public.html -->
{% extends "person/public.html" %}

{% block player_public %}
                    <div class="label">
                        <label for="id_icon">YOUR QWIKGAME REPUTATION</label>
                        <div class="button info sml push_right" data-visible="false">
                            <i class="fa-solid fa-info fa-1x" aria-hidden="true"></i>
                            <div class="info_text hidden">Based on feedback given by your rivals</div>
                        </div>
                    </div>
                    <div class="plank">
                        {% for _ in '12345'|make_list %} 
                        <div class="icon color">
                            {% if forloop.counter <= reputation %}
                            <i class="fa-solid fa-star fa-2x"></i>
                            {% else %}
                            <i class="fa-regular fa-star fa-2x"></i>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="label">
                        <label for="pecis">ABOUT</label>
                    </div>
                    <div class="tab_area post">
                        <div class="tabs">
                        {% for p in precis %}
                        <div class="button tab thin {% if forloop.counter0 == 0 %}active{% endif %}" data-tab_id="id_{{ p.game.code }}">
                            {{ p.game }}
                        </div>
                        {% endfor %}
                        </div>
                        {{ precis_form }}
                    </div>
                    {{ player_form }}
{% endblock %}